// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaMusica.Infrastructure.OutpointAdapter.Database.Sql.SqlServer;

#nullable disable

namespace TiendaMusica.Infrastructure.OutpointAdapter.Database.Sql.SqlServer.Migrations
{
    [DbContext(typeof(InstrumentSqlServerDbContext))]
    [Migration("20260529205328_AddUniqueIndexOnProductName")]
    partial class AddUniqueIndexOnProductName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TiendaMusica.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", "ms-product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDateUtc = new DateTime(2026, 5, 29, 20, 53, 27, 880, DateTimeKind.Utc).AddTicks(2771),
                            Description = "Instrumentos musicales",
                            Name = "Instrumentos"
                        });
                });

            modelBuilder.Entity("TiendaMusica.Domain.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products", "ms-product");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TiendaMusica.Domain.Models.Instrument", b =>
                {
                    b.HasBaseType("TiendaMusica.Domain.Models.Product");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.ToTable("Instruments", "ms-product");
                });

            modelBuilder.Entity("TiendaMusica.Domain.Models.Product", b =>
                {
                    b.HasOne("TiendaMusica.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TiendaMusica.Domain.Models.Instrument", b =>
                {
                    b.HasOne("TiendaMusica.Domain.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("TiendaMusica.Domain.Models.Instrument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TiendaMusica.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
